"""add filesize to indexed_file

Revision ID: 0b51c7a378f7
Revises: 8d31e3c0020b
Create Date: 2026-05-07 17:29:30.871121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b51c7a378f7'
down_revision = '8d31e3c0020b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filesize', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('last_accessed', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.drop_column('last_accessed')
        batch_op.drop_column('filesize')

    # ### end Alembic commands ###
