"""made 

Revision ID: 70fe643ab71a
Revises: a71932dc7b51
Create Date: 2025-04-01 01:56:26.363976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fe643ab71a'
down_revision = 'a71932dc7b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indexed_file', schema=None) as batch_op:
        batch_op.drop_constraint('indexed_file_filepath_key', type_='unique')

    # ### end Alembic commands ###


import { MigrationBuilder } from 'node-pg-migrate';

export function up(pgm: MigrationBuilder): void {
  pgm.createTable('users', {
    id: 'id',
    created_at: { type: 'timestamp', notNull: true, default: pgm.func('current_timestamp') },
    updated_at: { type: 'timestamp', notNull: true, default: pgm.func('current_timestamp') },
    email: { type: 'varchar(1000)', notNull: true, unique: true },
    password_hash: { type: 'varchar(100)', notNull: true },
    first_name: { type: 'varchar(100)' },
    last_name: { type: 'varchar(100)' },
    is_admin: { type: 'boolean', notNull: true, default: false },
  });

  pgm.createIndex('users', 'email');
}

export function down(pgm: MigrationBuilder): void {
  pgm.dropTable('users');
}
